# Webhook Handler Template
# Receive and process webhook requests
#
# Trigger URL: POST {kestra}/api/v1/executions/webhook/{namespace}/{flowId}/{key}
# Example: POST http://localhost:8081/api/v1/executions/webhook/automations/webhook-handler/my-secret-key

id: webhook-handler
namespace: automations
description: |
  Handle incoming webhook requests.
  Process the payload and take action based on content.

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "my-secret-key"  # Change this to a secure key

tasks:
  - id: log_received
    type: io.kestra.plugin.core.log.Log
    message: |
      Webhook received!
      Trigger: {{ trigger }}
      Body: {{ trigger.body }}

  - id: parse_payload
    type: io.kestra.plugin.scripts.python.Commands
    commands:
      - python process.py
    inputFiles:
      process.py: |
        import json
        import os

        # Access webhook body from trigger
        body = '''{{ trigger.body }}'''

        try:
            payload = json.loads(body) if body else {}

            # Process based on payload type
            event_type = payload.get('type', 'unknown')
            data = payload.get('data', {})

            print(f"Event Type: {event_type}")
            print(f"Data: {json.dumps(data, indent=2)}")

            # Output result
            result = {
                "event_type": event_type,
                "processed": True,
                "items_count": len(data) if isinstance(data, (list, dict)) else 0
            }

            with open('result.json', 'w') as f:
                json.dump(result, f)

        except json.JSONDecodeError:
            print("Warning: Body is not valid JSON")
            with open('result.json', 'w') as f:
                json.dump({"event_type": "raw", "processed": True}, f)
    outputFiles:
      - result.json

  - id: route_event
    type: io.kestra.plugin.core.flow.Switch
    value: "{{ read(outputs.parse_payload.outputFiles['result.json']) | json | jq('.event_type') }}"
    cases:
      user_created:
        - id: handle_user_created
          type: io.kestra.plugin.core.log.Log
          message: "Processing new user creation event"
      order_placed:
        - id: handle_order
          type: io.kestra.plugin.core.log.Log
          message: "Processing new order event"
    defaults:
      - id: handle_default
        type: io.kestra.plugin.core.log.Log
        message: "Received event with no specific handler"

  - id: log_complete
    type: io.kestra.plugin.core.log.Log
    message: "Webhook processing complete"
